# Generated by Django 4.2.18 on 2025-01-19 21:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_ID', models.CharField(max_length=10, unique=True)),
                ('Department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_ID', models.CharField(editable=False, max_length=10, unique=True)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Doctor_Email', models.EmailField(max_length=100, unique=True)),
                ('Doctor_Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Doctor_Age', models.IntegerField(validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(80)])),
                ('Doctor_Phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('Doctor_Address', models.TextField()),
                ('Specialization', models.CharField(max_length=100)),
                ('Experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['Last_Name', 'First_Name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('Medicine_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Medical_Type', models.CharField(max_length=255)),
                ('Buy_Price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('Sell_Price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('Batch_No', models.CharField(max_length=255)),
                ('Shelf_No', models.CharField(max_length=255)),
                ('Expire_Date', models.DateField()),
                ('Manufacturing_Date', models.DateField()),
                ('Description', models.TextField(blank=True)),
                ('In_Stock_Total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_ID', models.CharField(editable=False, max_length=10, unique=True)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Patient_Email', models.EmailField(max_length=100, unique=True)),
                ('Patient_Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Patient_Age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('Patient_Phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('Address', models.TextField()),
            ],
            options={
                'ordering': ['Last_Name', 'First_Name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prescription_ID', models.CharField(max_length=10, unique=True)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Dosage', models.CharField(max_length=100)),
                ('Frequency', models.CharField(max_length=100)),
                ('Refills', models.IntegerField()),
                ('Instructions', models.TextField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('Medicine_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicine')),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('Bill_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Total_Cost', models.CharField(max_length=255)),
                ('Payment_Status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=100)),
                ('Date_of_Bill', models.DateField()),
                ('Due_Date', models.DateField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appointment_ID', models.CharField(max_length=10, unique=True)),
                ('Status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=10)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Booked_on', models.DateField(auto_now=True)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app.patient')),
            ],
            options={
                'ordering': ['-Date', '-Time'],
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('Doctor', 'Date', 'Time'), name='Unique_Appointment'),
        ),
    ]
